apiVersion: scaffolder.backstage.io/v1beta3
kind: Template

metadata:
  name: doc-website-template
  title: A More Human-Readable Title
  description: This template does nothing and has no usage but being example in the documentation.
  tags:
    - example
    - gold
    - edu
  links:
    - url: https://admin.example-org.com
      title: Admin Dashboard
      icon: dashboard
      type: admin-dashboard

spec:
  type: website
  lifecycle: production
  owner: employee.ldap@homedepot.com
  system: public-websites

  steps:
    - action: debug:log
